Fix workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -31,7 +31,13 @@ jobs:
       - name: Get Version
         id: get_version
         run: |
-          VERSION_NAME=$(grep 'versionName' app/build.gradle | sed 's/[^0-9.]//g')
+          echo "Extracting versionName..."
+          VERSION_NAME=$(grep 'versionName =' app/build.gradle | sed -n 's/.*versionName = "\(.*\)"/\1/p')
+          if [ -z "$VERSION_NAME" ]; then
+            echo "Error: versionName not found or invalid format"
+            exit 1
+          fi
+          echo "Extracted VERSION_NAME=$VERSION_NAME"
           echo "VERSION=$VERSION_NAME" >> $GITHUB_ENV
 
       - name: Make Gradle Wrapper Executable
@@ -54,5 +60,6 @@ jobs:
           files: ${{ steps.releaseApk.outputs.apkfile }}
           draft: false
           prerelease: false
+          make_latest: true
           tag_name: ${{ env.VERSION }}
           name: Release ${{ env.VERSION }}
